// In-memory mock "database" for the school bags catalog.
// Prices/discounts/badges mirror the structure seen in the reference collection page.

export let products = [
  {
    id: "SB-001",
    title: "Kids School Bag",
    sku: "ACE-PINK-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "ACE",
    originalPrice: 3799,
    discountedPrice: 2849,
    discountPercent: 25,
    badge: null,
    inStock: true,
    isNew: false,
    color: "Pink",
    image: "https://placehold.co/500x500/ec4899/ffffff?text=ACE+Pink+Bag",
    rating: 4.4,
    reviewsCount: 18
  },
  {
    id: "SB-002",
    title: "Kids School Bag",
    sku: "ACE-BLACK-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "ACE",
    originalPrice: 3799,
    discountedPrice: 2849,
    discountPercent: 25,
    badge: null,
    inStock: true,
    isNew: false,
    color: "Black",
    image: "https://placehold.co/500x500/1f2937/ffffff?text=ACE+Black+Bag",
    rating: 4.6,
    reviewsCount: 27
  },
  {
    id: "SB-003",
    title: "Kids School Bag",
    sku: "ACE-BLUE-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "ACE",
    originalPrice: 3799,
    discountedPrice: 2849,
    discountPercent: 25,
    badge: null,
    inStock: true,
    isNew: false,
    color: "Blue",
    image: "https://placehold.co/500x500/2563eb/ffffff?text=ACE+Blue+Bag",
    rating: 4.5,
    reviewsCount: 21
  },
  {
    id: "SB-004",
    title: "Kids School Bag",
    sku: "PRINT-BUTTERFLY-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "Servis Kids",
    originalPrice: 3799,
    discountedPrice: 2849,
    discountPercent: 25,
    badge: "New",
    inStock: true,
    isNew: true,
    color: "Pink Multi",
    image: "https://placehold.co/500x500/db2777/ffffff?text=Butterfly+Print",
    rating: 4.3,
    reviewsCount: 9
  },
  {
    id: "SB-005",
    title: "Kids School Bag",
    sku: "PRINT-ROBOT-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "Servis Kids",
    originalPrice: 3799,
    discountedPrice: 2849,
    discountPercent: 25,
    badge: "New",
    inStock: true,
    isNew: true,
    color: "Blue Multi",
    image: "https://placehold.co/500x500/1d4ed8/ffffff?text=Robot+Print",
    rating: 4.2,
    reviewsCount: 6
  },
  {
    id: "SB-006",
    title: "Kids School Bag",
    sku: "PRINT-TEDDY-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "Servis Kids",
    originalPrice: 2999,
    discountedPrice: 2249,
    discountPercent: 25,
    badge: "New",
    inStock: true,
    isNew: true,
    color: "Pink Multi",
    image: "https://placehold.co/500x500/f472b6/ffffff?text=Teddy+Print",
    rating: 4.7,
    reviewsCount: 14
  },
  {
    id: "SB-007",
    title: "Kids School Bag",
    sku: "PRINT-MONSTERTRUCK-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "Servis Kids",
    originalPrice: 2999,
    discountedPrice: 2249,
    discountPercent: 25,
    badge: "Sold out",
    inStock: false,
    isNew: true,
    color: "Black Multi",
    image: "https://placehold.co/500x500/111827/ffffff?text=Monster+Truck",
    rating: 4.1,
    reviewsCount: 5
  },
  {
    id: "SB-008",
    title: "B-YO-0300023-School Bag",
    sku: "ACE-NAVY-YOUTH-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "ACE",
    originalPrice: 3199,
    discountedPrice: 2399,
    discountPercent: 25,
    badge: null,
    inStock: true,
    isNew: false,
    color: "Navy",
    image: "https://placehold.co/500x500/1e3a8a/ffffff?text=ACE+Navy+Youth",
    rating: 4.4,
    reviewsCount: 11
  },
  {
    id: "SB-009",
    title: "B-YO-0300023-School Bag",
    sku: "ACE-PINK-YOUTH-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "ACE",
    originalPrice: 3199,
    discountedPrice: 2399,
    discountPercent: 25,
    badge: null,
    inStock: true,
    isNew: false,
    color: "Pink",
    image: "https://placehold.co/500x500/e11d48/ffffff?text=ACE+Pink+Youth",
    rating: 4.3,
    reviewsCount: 8
  },
  {
    id: "SB-010",
    title: "B-YO-0300023-School Bag",
    sku: "ACE-BLACK-YOUTH-01",
    category: "kids",
    subcategory: "backpacks",
    brand: "ACE",
    originalPrice: 3199,
    discountedPrice: 2399,
    discountPercent: 25,
    badge: null,
    inStock: true,
    isNew: false,
    color: "Black",
    image: "https://placehold.co/500x500/000000/ffffff?text=ACE+Black+Youth",
    rating: 4.5,
    reviewsCount: 16
  }
];

export let orders = [];
export let nextOrderId = 1001;

export function pushOrder(order) {
  orders.push(order);
  nextOrderId += 1;
  return order;
}
